### ISSUE TITLE
No Build Instructions on Readme

### ISSUE THREAD

**Issue by chopradish** [archit120/3D-Graph#8]
No method of building, or proper details specified in Readme

**Comment by archit120** [comment]
Sorry, It's a VS2017 project. You don't need anything else to compile it.

**Comment by archit120** [comment]
I'm adding this to the readme and closing this issue. There is another one on documentation and we hope to have that ready in a week or two. We have a slack channel and would be excited to have you contribute : https://join.slack.com/t/3d-graph/shared_invite/enQtODI4Njk3MjkwOTEyLTQ1NGIwMzkwYzFhZThmM2ExZWUyOGYyMzE0YTVkYTVmM2NmMDI2MDE3Nzk1MThiYWZjYTM0NmE0NWVjOTM5YWE
